raw_data = [
    ### Test Data
    # {"iD":2,"Match":1,"Team":5924,"Alliance":5,"No Show":0,"Mobility":1,"Docked (Auto)":1,"Engaged (Auto)":1,"Score (Auto)":{"top":[0,0,0,0,0,0,0,0,0],"mid":[0,0,1,0,0,0,0,0,0],"botCone":[0,0,0,0,0,0,0,0,0],"botCube":[0,0,0,0,0,0,0,0,0]},"Score (Total)":{"top":[0,0,0,0,0,0,0,0,0],"mid":[0,0,1,0,0,0,0,0,0],"botCone":[0,0,0,0,0,0,0,0,0],"botCube":[1,1,0,0,0,0,1,1,1]},"Disabled":0,"Parked":0,"Docked (Endgame)":1,"Engaged (Endgame)":1,"Type":"qt"},
    # {"iD":2,"Match":1,"Team":971,"Alliance":4,"No Show":0,"Mobility":1,"Docked (Auto)":1,"Engaged (Auto)":1,"Score (Auto)":{"top":[0,0,0,0,0,0,0,0,0],"mid":[0,0,1,0,0,0,0,0,0],"botCone":[0,0,0,0,0,0,0,0,0],"botCube":[0,0,0,0,0,0,0,0,0]},"Score (Total)":{"top":[0,0,0,0,0,0,0,0,0],"mid":[0,0,1,0,0,0,0,0,0],"botCone":[0,0,0,0,0,0,0,0,0],"botCube":[1,1,0,0,0,0,1,1,1]},"Disabled":0,"Parked":0,"Docked (Endgame)":1,"Engaged (Endgame)":1,"Type":"qt"},
    # {"iD":2,"Match":1,"Team":254,"Alliance":0,"No Show":0,"Mobility":1,"Docked (Auto)":1,"Engaged (Auto)":1,"Score (Auto)":{"top":[0,0,0,0,0,0,0,0,0],"mid":[0,0,1,0,0,0,0,0,0],"botCone":[0,0,0,0,0,0,0,0,0],"botCube":[0,0,0,0,0,0,0,0,0]},"Score (Total)":{"top":[0,0,0,1,1,1,1,0,0],"mid":[0,0,1,0,0,0,0,0,0],"botCone":[0,0,0,0,0,0,0,0,0],"botCube":[1,1,0,0,0,0,1,1,1]},"Disabled":0,"Parked":0,"Docked (Endgame)":1,"Engaged (Endgame)":1,"Type":"qt"},
    # {"iD":2,"Match":2,"Team":5924,"Alliance":4,"Pieces Dropped":0,"Defense Rating":4,"Bumpers Fell Off?":0,"Climb Time > 15 sec?":1,"Type":"ql"},
    # {"iD":2,"Team":5924,"Alliance":0,"Speed (ft/sec)":14,"Drive Train":"Tank","Auto":"Docked & Engaged","Climb Time":"< 15 seconds","Substation":"Both","Ground Pickup or HP Station":"Both","Type":"pit"},

    ### Qualifications Data
    {"iD":21,"Match":26,"Team":1351,"Alliance":4,"No Show":0,"Mobility":1,"Docked (Auto)":0,"Engaged (Auto)":0,"Score (Auto)":{"top":[0,0,0,0,0,1,0,0,0],"mid":[0,0,0,0,0,0,0,0,0],"botCone":[0,0,0,0,0,0,0,0,0],"botCube":[0,0,0,0,0,0,0,0,0]},"Score (Total)":{"top":[0,0,0,1,1,0,0,0,0],"mid":[0,0,0,0,1,0,0,0,0],"botCone":[0,0,0,0,0,0,0,0,0],"botCube":[0,0,0,0,0,0,0,0,0]},"Disabled":0,"Parked":0,"Docked (Endgame)":0,"Engaged (Endgame)":0,"Type":"qt"},
    {"iD":25,"Match":26,"Team":9143,"Alliance":1,"Pieces Dropped":1,"Defense Rating":1,"Bumpers Fell Off?":0,"Climb Time > 15 sec?":0,"Type":"ql"},
    {"iD":25,"Match":26,"Team":9143,"Alliance":1,"No Show":0,"Mobility":1,"Docked (Auto)":0,"Engaged (Auto)":0,"Score (Auto)":{"top":[0,0,0,0,0,0,0,0,0],"mid":[0,0,0,0,0,0,0,0,0],"botCone":[0,0,0,0,0,0,0,0,0],"botCube":[0,0,0,0,0,0,1,0,0]},"Score (Total)":{"top":[0,0,0,0,0,0,0,0,0],"mid":[0,0,0,0,1,0,0,0,0],"botCone":[0,0,0,0,0,0,0,0,0],"botCube":[0,0,1,0,1,0,0,0,0]},"Disabled":0,"Parked":0,"Docked (Endgame)":0,"Engaged (Endgame)":1,"Type":"qt"},

    ### Pit Data ###
    {"iD":5,"Team":9038,"Speed (ft/sec)":12,"Drive Train":"Tank","Auto":"Place Game Pieces","Climb Time":"> 15 seconds","Substation":"Double","Ground Pickup or HP Station":"HP Station","Type":"pit"},
	{"iD":5,"Team":9114,"Speed (ft/sec)":None,"Drive Train":"Tank","Auto":"Docked & Engaged","Climb Time":"< 15 seconds","Substation":"Single","Ground Pickup or HP Station":"Ground Pickup","Type":"pit"},
	{"iD":5,"Team":9125,"Speed (ft/sec)":15,"Drive Train":"Tank","Auto":"Place Game Pieces","Climb Time":"","Substation":"Double","Ground Pickup or HP Station":"HP Station","Type":"pit"},
	{"iD":5,"Team":581,"Speed (ft/sec)":14,"Drive Train":"Swerve","Auto":"Docked & Engaged","Climb Time":"< 15 seconds","Substation":"Double","Ground Pickup or HP Station":"Ground Pickup","Type":"pit"},
	{"iD":5,"Team":None,"Speed (ft/sec)":None,"Drive Train":"Tank","Auto":"Place Game Pieces","Climb Time":"< 15 seconds","Substation":"Both","Ground Pickup or HP Station":"Both","Type":"pit"},
	{"iD":5,"Team":299,"Speed (ft/sec)":14,"Drive Train":"Swerve","Auto":"Place Game Pieces","Climb Time":"< 15 seconds","Substation":"Both","Ground Pickup or HP Station":"HP Station","Type":"pit"},
    {"iD":5,"Team":115,"Speed (ft/sec)":None,"Drive Train":"Swerve","Auto":"Place Game Pieces","Climb Time":"< 15 seconds","Substation":"Both","Ground Pickup or HP Station":"Both","Type":"pit"},
	{"iD":5,"Team":8169,"Speed (ft/sec)":None,"Drive Train":"Tank","Auto":"Place Game Pieces","Climb Time":"< 15 seconds","Substation":"Both","Ground Pickup or HP Station":"Both","Type":"pit"},
    {"iD":5,"Team":841,"Speed (ft/sec)":20,"Drive Train":"Tank","Auto":"No Auto","Climb Time":"< 15 seconds","Substation":"","Ground Pickup or HP Station":"","Type":"pit"},
    {"iD":5,"Team":8840,"Speed (ft/sec)":14,"Drive Train":"Swerve","Auto":"Docked & Engaged","Climb Time":"","Substation":"Both","Ground Pickup or HP Station":"Both","Type":"pit"},
    {"iD":5,"Team":649,"Speed (ft/sec)":16,"Drive Train":"Swerve","Auto":"Docked & Engaged","Climb Time":"< 15 seconds","Substation":"Double","Ground Pickup or HP Station":"HP Station","Type":"pit"},
    {"iD":5,"Team":8852,"Speed (ft/sec)":16,"Drive Train":"Tank","Auto":"Place Game Pieces","Climb Time":"","Substation":"Both","Ground Pickup or HP Station":"HP Station","Type":"pit"},
    {"iD":5,"Team":9006,"Speed (ft/sec)":None,"Drive Train":"Tank","Auto":"Docked & Engaged","Climb Time":"< 15 seconds","Substation":"Both","Ground Pickup or HP Station":"Ground Pickup","Type":"pit"},
    {"iD":5,"Team":972,"Speed (ft/sec)":12,"Drive Train":"Swerve","Auto":"Docked & Engaged","Climb Time":"< 15 seconds","Substation":"Both","Ground Pickup or HP Station":"Both","Type":"pit"},
    {"iD":5,"Team":8045,"Speed (ft/sec)":None,"Drive Train":"Tank","Auto":"Place Game Pieces","Climb Time":"< 15 seconds","Substation":"Both","Ground Pickup or HP Station":"Both","Type":"pit"},
    {"iD":5,"Team":2854,"Speed (ft/sec)":14,"Drive Train":"Swerve","Auto":"Docked & Engaged","Climb Time":"< 15 seconds","Substation":"Both","Ground Pickup or HP Station":"Both","Type":"pit"},
    {"iD":5,"Team":4186,"Speed (ft/sec)":None,"Drive Train":"Tank","Auto":"Mobility","Climb Time":"> 15 seconds","Substation":"Double","Ground Pickup or HP Station":"Both","Type":"pit"},
    {"iD":5,"Team":4669,"Speed (ft/sec)":10,"Drive Train":"Tank","Auto":"Place Game Pieces","Climb Time":"> 15 seconds","Substation":"Double","Ground Pickup or HP Station":"HP Station","Type":"pit"},
    {"iD":5,"Team":6418,"Speed (ft/sec)":15,"Drive Train":"Tank","Auto":"Mobility","Climb Time":"> 15 seconds","Substation":"Double","Ground Pickup or HP Station":"Both","Type":"pit"},
    {"iD":5,"Team":4765,"Speed (ft/sec)":10,"Drive Train":"Swerve","Auto":"Place Game Pieces","Climb Time":"","Substation":"Both","Ground Pickup or HP Station":"Both","Type":"pit"},
    {"iD":5,"Team":4904,"Speed (ft/sec)":15,"Drive Train":"Tank","Auto":"Docked & Engaged","Climb Time":"","Substation":"Both","Ground Pickup or HP Station":"Both","Type":"pit"},
    {"iD":5,"Team":5507,"Speed (ft/sec)":None,"Drive Train":"Swerve","Auto":"Docked & Engaged","Climb Time":"< 15 seconds","Substation":"Single","Ground Pickup or HP Station":"HP Station","Type":"pit"},
    {"iD":5,"Team":114,"Speed (ft/sec)":9,"Drive Train":"Swerve","Auto":"Place Game Pieces","Climb Time":"< 15 seconds","Substation":"Double","Ground Pickup or HP Station":"Both","Type":"pit"},
    {"iD":5,"Team":971,"Speed (ft/sec)":17,"Drive Train":"Tank","Auto":"Place Game Pieces","Climb Time":"< 15 seconds","Substation":"Both","Ground Pickup or HP Station":"Both","Type":"pit"},
    {"iD":5,"Team":604,"Speed (ft/sec)":None,"Drive Train":"Swerve","Auto":"Place Game Pieces","Climb Time":"< 15 seconds","Substation":"Single","Ground Pickup or HP Station":"Ground Pickup","Type":"pit"},
    {"iD":5,"Team":8751,"Speed (ft/sec)":None,"Drive Train":"Tank","Auto":"Place Game Pieces","Climb Time":"","Substation":"Both","Ground Pickup or HP Station":"Both","Type":"pit"},
    {"iD":5,"Team":8793,"Speed (ft/sec)":23,"Drive Train":"Tank","Auto":"Docked & Engaged","Climb Time":"< 15 seconds","Substation":"Single","Ground Pickup or HP Station":"Ground Pickup","Type":"pit"},
    {"iD":5,"Team":1351,"Speed (ft/sec)":14,"Drive Train":"Swerve","Auto":"Docked & Engaged","Climb Time":"","Substation":"Both","Ground Pickup or HP Station":"Both","Type":"pit"},
    {"iD":5,"Team":9143,"Speed (ft/sec)":None,"Drive Train":"Tank","Auto":"Docked & Engaged","Climb Time":"< 15 seconds","Substation":"Double","Ground Pickup or HP Station":"Ground Pickup","Type":"pit"},
    {"iD":5,"Team":5430,"Speed (ft/sec)":None,"Drive Train":"Tank","Auto":"Docked & Engaged","Climb Time":"< 15 seconds","Substation":"Single","Ground Pickup or HP Station":"Both","Type":"pit"},
    {"iD":5,"Team":3045,"Speed (ft/sec)":13,"Drive Train":"Tank","Auto":"Place Game Pieces","Climb Time":"","Substation":"Both","Ground Pickup or HP Station":"Ground Pickup","Type":"pit"},
    {"iD":5,"Team":6619,"Speed (ft/sec)":None,"Drive Train":"Tank","Auto":"No Auto","Climb Time":"","Substation":"Single","Ground Pickup or HP Station":"Both","Type":"pit"},
    {"iD":5,"Team":8016,"Speed (ft/sec)":None,"Drive Train":"Tank","Auto":"Place Game Pieces","Climb Time":"< 15 seconds","Substation":"Both","Ground Pickup or HP Station":"Both","Type":"pit"},
    {"iD":5,"Team":4159,"Speed (ft/sec)":None,"Drive Train":"Swerve","Auto":"Docked & Engaged","Climb Time":"< 15 seconds","Substation":"Both","Ground Pickup or HP Station":"Both","Type":"pit"},
    {"iD":5,"Team":6962,"Speed (ft/sec)":12,"Drive Train":"Tank","Auto":"Docked & Engaged","Climb Time":"","Substation":"Double","Ground Pickup or HP Station":"Both","Type":"pit"},
    {"iD":12,"Team":9111,"Speed (ft/sec)":None,"Drive Train":"Tank","Auto":"Place Game Pieces","Climb Time":"","Substation":"Single","Ground Pickup or HP Station":"Both","Type":"pit"},
    {"iD":12,"Team":1967,"Speed (ft/sec)":None,"Drive Train":"Tank","Auto":"Docked & Engaged","Climb Time":"< 15 seconds","Substation":"Single","Ground Pickup or HP Station":"Ground Pickup","Type":"pit"},
    {"iD":12,"Team":7245,"Speed (ft/sec)":None,"Drive Train":"Tank","Auto":"","Climb Time":"","Substation":"","Ground Pickup or HP Station":"","Type":"pit"},
    {"iD":12,"Team":5700,"Speed (ft/sec)":17,"Drive Train":"Tank","Auto":"Docked & Engaged","Climb Time":"> 15 seconds","Substation":"Single","Ground Pickup or HP Station":"Both","Type":"pit"},
    {"iD":12,"Team":5419,"Speed (ft/sec)":16,"Drive Train":"Swerve","Auto":"Docked & Engaged","Climb Time":"< 15 seconds","Substation":"Single","Ground Pickup or HP Station":"Both","Type":"pit"},
    {"iD":12,"Team":1700,"Speed (ft/sec)":14,"Drive Train":"Swerve","Auto":"Place Game Pieces","Climb Time":"< 15 seconds","Substation":"Double","Ground Pickup or HP Station":"Both","Type":"pit"},
]